version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      args:
        APP_NAME: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - realtime-gateway
      - chat
      - user
      - notification
      - redis
      - rabbitmq

  realtime-gateway:
    build:
      context: .
      dockerfile: ./apps/realtime-gateway/Dockerfile
      args:
        APP_NAME: realtime-gateway
    depends_on:
      - redis
      - rabbitmq

  chat:
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
      args:
        APP_NAME: chat
    depends_on:
      - rabbitmq
      - redis

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      args:
        APP_NAME: user
    depends_on:
      - rabbitmq

  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      args:
        APP_NAME: notification
    depends_on:
      - rabbitmq

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
